Repository openscilab/pymilo, pull requests merged in 2023-12, with the labels that each got.

#56 Minor edits
  .github/dependabot.yml
  codecov.yml
  otherfiles/version_check.py
  pymilo/chains/clustering_chain.py
  pymilo/chains/decision_tree_chain.py
  pymilo/chains/linear_model_chain.py
  pymilo/chains/neural_network_chain.py
  pymilo/exceptions/deserialize_exception.py
  pymilo/exceptions/serialize_exception.py
  pymilo/pymilo_func.py
  pymilo/transporters/general_data_structure_transporter.py
  pymilo/transporters/labelbinarizer_transporter.py
  pymilo/transporters/transporter.py
  tests/test_clusterings/test_clusterings.py
  tests/test_decision_trees/test_decision_trees.py
  tests/test_exceptions/test_exceptions.py
  tests/test_linear_models/test_linear_models.py
  tests/test_neural_networks/test_neural_networks.py
Labels: minor, refactoring

#60 Minor edits
  autopep8.bat
  autopep8.sh
  otherfiles/RELEASE.md
Labels: documentation, test, minor

#61 Update docs
  CHANGELOG.md
  README.md
  SUPPORTED_MODELS.md
Labels: minor

#62 Feature/hdbscan support
  CHANGELOG.md
  pymilo/pymilo_param.py
  pymilo/transporters/tree_transporter.py
  pymilo/utils/data_exporter.py
  pymilo/utils/test_pymilo.py
  tests/test_clusterings/hdbscan.py
  tests/test_clusterings/test_clusterings.py
Labels: minor
