Repository openscilab/pymilo, pull requests merged in 2023-06, with the labels that each got.

#8 Readme and Workflows
  .github/workflows/publish_pypi.yml
  .github/workflows/test.yml
  README.md
  TODO.md
  otherfiles/donation.png
  otherfiles/meta.yaml
  otherfiles/version_check.py
Labels: documentation, script, test

#9 Minor edits
  AUTHORS.md
  README.md
Labels: documentation

#11 Logo crop
  README.md
  otherfiles/logo.png
Labels: documentation

#14 Release instructions
  CHANGELOG.md
  otherfiles/RELEASE.md
Labels: documentation

#15 Version 0.1
  CHANGELOG.md
  pymilo/pymilo_param.py
Labels: release
