Repository openscilab/pymilo, pull requests merged in 2023-11, with the labels that each got.

#49 Clustering/regular models
  .github/workflows/test.yml
  CHANGELOG.md
  SUPPORTED_MODELS.md
  pymilo/pymilo_param.py
  tests/test_clusterings/affinity_propagation.py
  tests/test_clusterings/dbscan.py
  tests/test_clusterings/gaussian_mixture/gaussian_mixture.py
  tests/test_clusterings/hierarchical_clustering/agglomerative_clustering.py
  tests/test_clusterings/mean_shift.py
  tests/test_clusterings/optics.py
  tests/test_clusterings/spectral_clustering.py
  tests/test_clusterings/test_clusterings.py
Labels: new feature, minor

#50 Python 3.12
  .github/workflows/test.yml
  CHANGELOG.md
  setup.py
Labels: test, minor

#51 Requirements bug
  CHANGELOG.md
  dev-requirements.txt
Labels: bug, test, minor

#52 Code quality badges
  CHANGELOG.md
  README.md
Labels: documentation, test, minor
