Repository openscilab/pymilo, pull requests merged in 2024-01, with the labels that each got.

#63 FeatureAgglomeration addition
  CHANGELOG.md
  pymilo/chains/clustering_chain.py
  pymilo/pymilo_param.py
  pymilo/transporters/function_transporter.py
  pymilo/utils/util.py
  tests/test_clusterings/hierarchical_clustering/feature_agglomeration.py
  tests/test_clusterings/test_clusterings.py
Labels: new feature, minor

#65 BayesianGaussianMixture model addition
  CHANGELOG.md
  pymilo/pymilo_param.py
  pymilo/transporters/general_data_structure_transporter.py
  tests/test_clusterings/gaussian_mixture/bayesian_gaussian_mixture.py
  tests/test_clusterings/test_clusterings.py
Labels: new feature, minor

#64 Modern issue/feature template
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CHANGELOG.md
  otherfiles/RELEASE.md
  otherfiles/version_check.py
  setup.py
Labels: documentation, enhancement, minor

#66 Feature/BisectingKMeans
  pymilo/chains/clustering_chain.py
  pymilo/pymilo_param.py
  pymilo/transporters/bisecting_tree_transporter.py
  pymilo/transporters/general_data_structure_transporter.py
  pymilo/utils/test_pymilo.py
  tests/test_clusterings/bisecting_kmeans.py
  tests/test_clusterings/gaussian_mixture/bayesian_gaussian_mixture.py
  tests/test_clusterings/test_clusterings.py
Labels: bug, enhancement, new feature, major, refactoring

#68 Feature/otherSpectralClusterings+MiniBatchKMeans
  CHANGELOG.md
  SUPPORTED_MODELS.md
  pymilo/pymilo_param.py
  pymilo/transporters/function_transporter.py
  tests/test_clusterings/minibatch_kmeans.py
  tests/test_clusterings/spectral_clustering/spectral_biclustering.py
  tests/test_clusterings/spectral_clustering/spectral_clustering.py
  tests/test_clusterings/spectral_clustering/spectral_coclustering.py
  tests/test_clusterings/test_clusterings.py
Labels: enhancement, minor

#69 Feature/Birch
  CHANGELOG.md
  SUPPORTED_MODELS.md
  pymilo/chains/clustering_chain.py
  pymilo/pymilo_param.py
  pymilo/transporters/cfnode_transporter.py
  pymilo/utils/util.py
  tests/test_clusterings/birch.py
  tests/test_clusterings/test_clusterings.py
Labels: enhancement, new feature, major

#71 Version 0.4
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  otherfiles/meta.yaml
  otherfiles/version_check.py
  pymilo/pymilo_param.py
  setup.py
Labels: release

#74 Generalize loss_function serializer
  pymilo/transporters/lossfunction_transporter.py
Labels: bug, enhancement

#75 Feature/naive bayes
  .gitignore
  CHANGELOG.md
  README.md
  SUPPORTED_MODELS.md
  pymilo/chains/naive_bayes_chain.py
  pymilo/pymilo_func.py
  pymilo/pymilo_param.py
  pymilo/transporters/general_data_structure_transporter.py
  pymilo/utils/test_pymilo.py
  tests/test_naive_bayes/bernoulli.py
  tests/test_naive_bayes/categorical.py
  tests/test_naive_bayes/complement.py
  tests/test_naive_bayes/gaussian.py
  tests/test_naive_bayes/multinomial.py
  tests/test_naive_bayes/test_naive_bayes_models.py
Labels: enhancement, new feature, minor

#77 Transport root_ before dummy_leaf_
  .github/workflows/test.yml
  CHANGELOG.md
  pymilo/transporters/cfnode_transporter.py
  pymilo/transporters/general_data_structure_transporter.py
  pymilo/transporters/transporter.py
Labels: enhancement, minor

#78 Version 0.5
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  otherfiles/meta.yaml
  otherfiles/version_check.py
  pymilo/pymilo_param.py
  setup.py
Labels: release
