Repository openscilab/pymilo, pull requests merged in 2024-04, with the labels that each got.

#89 Feature/ensemble_transporters
  pymilo/transporters/binmapper_transporter.py
  pymilo/transporters/bunch_transporter.py
  pymilo/transporters/generator_transporter.py
  pymilo/transporters/labelencoder_transporter.py
  pymilo/transporters/onehotencoder_transporter.py
  pymilo/transporters/treepredictor_transporter.py
Labels: new feature

#90 Feature/enhance prior transporters
  pymilo/pymilo_param.py
  pymilo/transporters/bunch_transporter.py
  pymilo/transporters/general_data_structure_transporter.py
  pymilo/transporters/lossfunction_transporter.py
  pymilo/transporters/onehotencoder_transporter.py
  pymilo/transporters/transporter.py
Labels: enhancement

#93 Support Ensemble Models
  .gitignore
  CHANGELOG.md
  README.md
  SUPPORTED_MODELS.md
  pymilo/chains/clustering_chain.py
  pymilo/chains/decision_tree_chain.py
  pymilo/chains/ensemble_chain.py
  pymilo/chains/linear_model_chain.py
  pymilo/chains/naive_bayes_chain.py
  pymilo/chains/neighbours_chain.py
  pymilo/chains/neural_network_chain.py
  pymilo/chains/svm_chain.py
  pymilo/chains/util.py
  pymilo/pymilo_func.py
  pymilo/pymilo_obj.py
  pymilo/pymilo_param.py
  pymilo/transporters/lossfunction_transporter.py
  pymilo/transporters/transporter.py
  pymilo/utils/test_pymilo.py
  pymilo/utils/util.py
  tests/test_ensembles/adaboost/adaboost_classifier.py
  tests/test_ensembles/adaboost/adaboost_regressor.py
  tests/test_ensembles/bagging/bagging_classifier.py
  tests/test_ensembles/bagging/bagging_regressor.py
  tests/test_ensembles/extra_trees/extra_trees_classifier.py
  tests/test_ensembles/extra_trees/extra_trees_regressor.py
  tests/test_ensembles/gradient_booster/gradient_booster_classifier.py
  tests/test_ensembles/gradient_booster/gradient_booster_regressor.py
  tests/test_ensembles/hist_gradient_boosting/hist_gradient_boosting_classifier.py
  tests/test_ensembles/hist_gradient_boosting/hist_gradient_boosting_regressor.py
  tests/test_ensembles/isolation_forest.py
  tests/test_ensembles/pipeline.py
  tests/test_ensembles/random_forests/random_forest_classifier.py
  tests/test_ensembles/random_forests/random_forest_regressor.py
  tests/test_ensembles/random_trees_embedding.py
  tests/test_ensembles/stacking/stacking_classifier.py
  tests/test_ensembles/stacking/stacking_regressor.py
  tests/test_ensembles/test_ensembles.py
  tests/test_ensembles/voting/voting_classifier.py
  tests/test_ensembles/voting/voting_regressor.py
Labels: enhancement, new feature, major

#96 Minor edits
  README.md
  SUPPORTED_MODELS.md
Labels: documentation, minor

#97 SECURITY.md
  .github/workflows/test.yml
  CHANGELOG.md
  SECURITY.md
  otherfiles/RELEASE.md
  otherfiles/version_check.py
Labels: documentation, minor
