Repository openscilab/pymilo, pull requests merged in 2024-06, with the labels that each got.

#104 Feature:: Preprocessing models
  .gitignore
  CHANGELOG.md
  README.md
  SUPPORTED_MODELS.md
  dev-requirements.txt
  otherfiles/meta.yaml
  pymilo/pymilo_param.py
  pymilo/transporters/function_transporter.py
  pymilo/transporters/general_data_structure_transporter.py
  pymilo/transporters/preprocessing_transporter.py
  pymilo/utils/util.py
  requirements.txt
  tests/test_preprocessings/binarizer.py
  tests/test_preprocessings/function_transformer.py
  tests/test_preprocessings/kbins_discretizer.py
  tests/test_preprocessings/kernel_centerer.py
  tests/test_preprocessings/label_binarizer.py
  tests/test_preprocessings/label_encoder.py
  tests/test_preprocessings/max_abs_scaler.py
  tests/test_preprocessings/multilabel_binarizer.py
  tests/test_preprocessings/normalizer.py
  tests/test_preprocessings/one_hot_encoder.py
  tests/test_preprocessings/ordinal_encoder.py
  tests/test_preprocessings/polynomial_features.py
  tests/test_preprocessings/power_transformer.py
  tests/test_preprocessings/quantile_transformer.py
  tests/test_preprocessings/robust_scaler.py
  tests/test_preprocessings/spline_transformer.py
  tests/test_preprocessings/standard_scaler.py
  tests/test_preprocessings/target_encoder.py
  tests/test_preprocessings/test_preprocessings.py
  tests/test_preprocessings/util.py
Labels: new feature, major

#105 Anaconda Workflow
  .github/workflows/publish_conda.yml
  CHANGELOG.md
  README.md
Labels: documentation, enhancement, minor

#108 Minor edits
  CHANGELOG.md
  README.md
  pymilo/chains/clustering_chain.py
  pymilo/chains/decision_tree_chain.py
  pymilo/chains/ensemble_chain.py
  pymilo/chains/linear_model_chain.py
  pymilo/chains/naive_bayes_chain.py
  pymilo/chains/neighbours_chain.py
  pymilo/chains/neural_network_chain.py
  pymilo/chains/svm_chain.py
  pymilo/exceptions/deserialize_exception.py
  pymilo/exceptions/pymilo_exception.py
  pymilo/exceptions/serialize_exception.py
  pymilo/pymilo_func.py
  pymilo/pymilo_obj.py
  pymilo/pymilo_param.py
  pymilo/transporters/adamoptimizer_transporter.py
  pymilo/transporters/baseloss_transporter.py
  pymilo/transporters/binmapper_transporter.py
  pymilo/transporters/general_data_structure_transporter.py
  pymilo/transporters/preprocessing_transporter.py
  pymilo/transporters/transporter.py
  pymilo/transporters/treepredictor_transporter.py
  pymilo/utils/data_exporter.py
Labels: documentation, enhancement, minor

#110 Version 0.9
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  otherfiles/meta.yaml
  otherfiles/version_check.py
  pymilo/pymilo_param.py
  setup.py
Labels: release
